### ISSUE TITLE
Builds Don't Work with Node v17 Release

### ISSUE THREAD

**Issue by ralfisalhon** [postcss/postcss-safe-parser#29]
In Node v17:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /tmp/workspace/node_modules/postcss-safe-parser/node_modules/postcss/package.json
```

In earlier versions of Node, this was just a deprecation warning:
```
(node:3713) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /tmp/workspace/node_modules/postcss-safe-parser/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
```

**Comment by kanto2113** [comment]
@ai npm ls doesn't list PotsCSS.  The react-scripts npm module has the following as a dependencies.

    "postcss-flexbugs-fixes": "4.2.1",
    "postcss-loader": "3.0.0",
    "postcss-normalize": "8.0.1",
    "postcss-preset-env": "6.7.0",
    "postcss-safe-parser": "5.0.2"

**Comment by dantman** [comment]
> I do not really like to fixing my old releases because of CRA maintainers (it is not fair that I am working for them). But if somebody sends a well-tested PR to `v7` branch, I can release it.

Unfortunately there's no point to that. `react-scripts@4.0.3` has postcss-safe-parser pinned to `5.0.2` exactly. So even if make a new patch release it won't be installed.

It looks like CRA has already updated PostCSS to v8 and also removed `postcss-safe-parser` as part of the WebPack 5 update. However of course they haven't released any of the work done on CRA since Feb so we're stuck with this issue.

**Comment by cojack** [comment]
> Is there any fix for this?

yes, @timashov downgrade your node version to 16

**Comment by spykard** [comment]
Still occuring

**Comment by artginzburg** [comment]
Same issue here. Currently bypassing it by downgrading to Node LTS (16).

The thing is, the project I'm talking about cannot even be safely updated to a newer version, because it was ejected from CRA.

New apps built with CRA work fine on Node 18 though.

**Comment by byteshiva** [comment]
Failing for `Node v17.5.0`

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /home/xyz/sample/node_modules/postcss-safe-parser/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/xyz/sample/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by byteshiva** [comment]
> Failing for `Node v17.5.0`
> 
> ```
> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /home/xyz/sample/node_modules/postcss-safe-parser/node_modules/postcss/package.json
>     at new NodeError (node:internal/errors:371:5)
>     at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
>     at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
>     at resolveExports (node:internal/modules/cjs/loader:482:36)
>     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:999:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/xyz/sample/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17) {
>   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
> }
> ```

The below fix worked for me.

Update `postcss` on v17.5.0
```
npm install  postcss   
```

**Comment by cosmicknox** [comment]
> npm install  postcss

this worked for me thanks

**Comment by xanderjames1910** [comment]
I had the same issue and as many of you say, it's a problem with react-scripts and postcss because of React version.

I fixed it in my React app by removing node_modules folder and yarn.lock file, then I updated my React version and also my react-dom dependency with:

`yarn add react@latest react-dom@latest`

Then I ran `yarn` so my node_modules get installed again, which fixed my issue.

I hope this helps some of you. 

This worked for me because it's a small React App. You should probably verify if other dependencies are compatible with the latest React version (now 18.2.0)
