### ISSUE TITLE
Please use semver when you changing something

### ISSUE THREAD

**Issue by mdreizin** [postcss/postcss-safe-parser#3]
Please use [semver](http://semver.org) when you changing something.

Last `1.0.2` version introduces migration to `babel 6` https://github.com/postcss/postcss-safe-parser/commit/ea4ea71607ff82566c1371fa1f9edddb330690fe and it has breaking changes.

You had to use `MAJOR` instead of `PATCH`.

**Comment by mdreizin** [comment]
It should be true for all `postcss` projects.

**Comment by ai** [comment]
@mdreizin how Babel 6 changes public API?

**Comment by ai** [comment]
If public API was changed, we should fix it.

**Comment by mdreizin** [comment]
@ai Yes, a lot of changes. Please see:

http://babeljs.io/blog/2015/10/29/6.0.0/
http://babeljs.io/blog/2015/10/31/setting-up-babel-6/
https://phabricator.babeljs.io

It is good practices to use `MINOR` or `MAJOR` When you changing `dependencies`.

**Comment by mdreizin** [comment]
@ai It is not good to close issue without any investigation, because your changes affect a lot of users.

**Comment by ai** [comment]
@mdreizin do you know, that `postcss` do not contain Babel in npm package. Babel is used only in development to prepare ES5 build.

All tests showed that ES5 build by Babel 6 is same that ES5 build by Babel 5.

What changes do you find in ES5 build by Babel 6?
