### ISSUE TITLE
when used with CRA, deprecated warning in node 16

### ISSUE THREAD

**Issue by bdefore** [postcss/postcss-safe-parser#31]
When running Create React App v5 (which uses postcss-safe-parser 5.0.2) on Node 16 I see the following warning:

`(node:297110) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /home/REDACTED/code/REDACTED/web/node_modules/postcss-safe-parser/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".`

May be related to https://github.com/postcss/postcss-safe-parser/issues/29

**Comment by ai** [comment]
`postcss` 8 doesn’t use `./` https://github.com/postcss/postcss/blob/main/package.json#L8

It happens because you are using old out-of-support PostCSS version. Check `npm ls` and ask CRA to update dependencies.

**Comment by ai** [comment]
I am closing this issue since I am tiring of doing extra work because of bad CRA maintaining.

I fixed this bug and you see it because not all dependencies was updated by CRA maintainers (if you will explain to me that I am wrong, I will re-open an issue).
