### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by redblood639** [postcss/postcss-safe-parser#36]
Hi, How are you ?
Now I am trying to use `postcss-safe-parser` in my project. But I got warning from them.

"postcss-safe-parser": "^5.0.2",

```
[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\...\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```
I already tried all method that developers posted solving method. but I couldn't solve with them.
How can I solve this problem ?
I hope you let me know asap.
Thank you

**Comment by ai** [comment]
Update `postcss-safe-parser`

**Comment by redblood639** [comment]
Should I update to latest version ?

**Comment by ai** [comment]
Yes, before any bug report

**Comment by ai** [comment]
Check `peerDependencies` warnings. You need to update PostCSS together with `postcss-safe-parser`.

**Comment by redblood639** [comment]
Hmm.... Excuse me, Could you let me know in more detail ?
Because I didn't use PostCSS in my project, so I just tried to install package. yarn add postcss.
but there happened error.
![image](https://user-images.githubusercontent.com/72724141/229923502-a1e1a849-5f64-4aa1-ba1c-807d54924fbb.png)

How can I install package by using Yarn ?

**Comment by ai** [comment]
Sorry, I can’t help you with debugging your own application.

Seems like you are using monorepo and need to put `postcss-safe-parser` to the right sub-project (or use `-W` argument). Anyway it is out of the scope of this project and free help as open source developer.

**Comment by redblood639** [comment]
Thank You.
