### ISSUE TITLE
-bracket-: hack[; is failing

### ISSUE THREAD

**Issue by ldrick** [postcss/postcss-safe-parser#8]
Hi, I've got some legacy vendor css, which currently uses hack number 14 Test 4 from here: [http://mynthon.net/howto/-/webdev/CSS-big-list-of-css-hacks.txt](http://mynthon.net/howto/-/webdev/CSS-big-list-of-css-hacks.txt)

and which is curently not "safe parsed" to be further processed.
```
-bracket-: hack[;
    height: 25px;
];
```
currently becomes
```
-bracket-: hack[;;
    height: 25px;
]
```
which failes in css-loader.

**Comment by ai** [comment]
> which failes in css-loader.

Sorry, most of `postcss-safe-parser` output will fail `css-loader`.

The core idea is to parse it without error. Not to save byte-to-byte of fix the errors.

For me, this case is too rare and too crazy to do it, sorry :).

But if you will send a pull request which will fix `;` duplication, I will accept it.

**Comment by ldrick** [comment]
I'll fix this vendor package in a local repository and integrate my fixed version. Thanks for clearifying.
